name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.exxspes.space
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker Image
        run: |
          docker build -t harbor.exxspes.space/library/app:latest .
          docker push harbor.exxspes.space/library/app:latest

      - name: Copy docker compose
        run: mkdir build && rsync -az docker-compose.yml .env build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-build

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy artifacts to EC2 instance
        run: |
          ls -lha
          rsync -az -e "ssh -o StrictHostKeyChecking=no" docker-compose.yml .env root@54.172.84.0:/opt/my-project/

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no root@54.172.84.0 << 'EOF'
            docker pull harbor.exxspes.space/library/app:latest
            cd /opt/my-project
            docker compose down && docker compose up -d
          EOF
